# Generated by Django 3.0.2 on 2020-03-22 19:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=200, verbose_name='Заголовок документа')),
                ('doc_path', ckeditor.fields.RichTextField(default='https://slimexpert.github.io/zextel/pdf/', verbose_name='Полный путь до документа')),
                ('doc_pub', models.DateTimeField(verbose_name='Дата публикации документа')),
                ('doc_show', models.BooleanField(default=1, verbose_name='Отображать вакансию на сайте')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Наименование вакансии')),
                ('job_text', ckeditor.fields.RichTextField(default='Вакансия', verbose_name='Полный текст вакансии')),
                ('job_date', models.DateTimeField(verbose_name='Дата публикации вакансии')),
                ('job_show', models.BooleanField(default=1, verbose_name='Отображать вакансию на сайте')),
            ],
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(max_length=100, verbose_name='Заголовок новости')),
                ('new_title_text', models.CharField(max_length=100, verbose_name='Карткий текст')),
                ('new_text', ckeditor.fields.RichTextField(default='Поный текст', verbose_name='Полный текст')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации новости')),
                ('pub_main', models.BooleanField(default=1, verbose_name='Показывать на главной')),
                ('new_like', models.IntegerField(verbose_name='Лайк')),
            ],
        ),
    ]
