# Generated by Django 3.0.2 on 2020-04-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_path',
            field=models.CharField(default='https://slimexpert.github.io/zextel/pdf/', max_length=250, verbose_name='Полный путь до документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_show',
            field=models.BooleanField(default=1, verbose_name='Отображать документ на сайте'),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_like',
            field=models.IntegerField(default=1, verbose_name='Лайк'),
        ),
    ]
