# Generated by Django 3.0.2 on 2020-03-22 19:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='sl_text',
            field=ckeditor.fields.RichTextField(default='<div></div>', verbose_name='HTML сладера'),
        ),
    ]
