# Generated by Django 3.0.2 on 2020-04-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200322_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_name', models.CharField(max_length=50, verbose_name='Имя отправителя')),
                ('supp_email', models.EmailField(max_length=100, verbose_name='E-mail отправителя')),
                ('supp_tel', models.CharField(max_length=14, verbose_name='Телефон отправителя')),
                ('supp_cat', models.CharField(max_length=50, verbose_name='Имя отправителя')),
                ('supp_text', models.TextField(verbose_name='Текст обращения')),
                ('supp_otvet', models.BooleanField(default=1, verbose_name='Ответ на обращение')),
                ('supp_date', models.DateTimeField(verbose_name='Дата обращения')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
    ]
