# Generated by Django 3.0.2 on 2020-04-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200418_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_support',
            name='supp_cat',
            field=models.CharField(max_length=50, verbose_name='Категория обращения'),
        ),
        migrations.AlterField(
            model_name='contact_support',
            name='supp_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='contact_support',
            name='supp_otvet',
            field=models.CharField(max_length=50, verbose_name='Ответ на обращение'),
        ),
    ]
