# Generated by Django 3.0.2 on 2020-05-03 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200419_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_title', models.CharField(max_length=100, verbose_name='Наименование зоны')),
                ('zone_text', models.CharField(max_length=200, verbose_name='Описание')),
                ('zone_show', models.BooleanField(default=1, verbose_name='Учитывать')),
            ],
            options={
                'verbose_name': 'Зона охвата',
                'verbose_name_plural': 'Зоны охвата',
            },
        ),
        migrations.CreateModel(
            name='postal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=6, verbose_name='Индекс')),
                ('postal_title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('postal_show', models.BooleanField(default=1, verbose_name='Учитывать')),
                ('postal_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.zone')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
    ]
