# Generated by Django 3.0.2 on 2020-05-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_postal_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_summ',
            field=models.IntegerField(blank=True, default='6000', verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
