# Generated by Django 3.0.2 on 2020-05-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200504_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_number',
            field=models.IntegerField(blank=True, default='1', verbose_name='Порядок вывода'),
        ),
        migrations.AlterField(
            model_name='postal',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_summ',
            field=models.IntegerField(blank=True, default='6000', verbose_name='Стоимость'),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_title', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('rate_title_text', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('rate_group', models.IntegerField(verbose_name='Группа тарифов')),
                ('rate_number', models.IntegerField(verbose_name='Номер тарифа в группе')),
                ('rate_type', models.CharField(choices=[('МКД', 'Многоквартирный дом'), ('ЧД', 'Частный дом')], max_length=50, verbose_name='Тип тарифа')),
                ('rate_popular', models.BooleanField(default=0, verbose_name='Выделения популярю тарифа')),
                ('rate_speed', models.IntegerField(verbose_name='Скорость доступа')),
                ('rate_summ', models.FloatField(verbose_name='Стоиомсть')),
                ('rate_rate', models.FloatField(verbose_name='Рейтинг тарифа от 0 до 5')),
                ('rate_tv_show', models.BooleanField(default=0, verbose_name='Показывать ТВ каналы')),
                ('rate_tv_count', models.IntegerField(verbose_name='Количество каналов')),
                ('rate_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.zone')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
            },
        ),
    ]
