# Generated by Django 3.0.2 on 2020-06-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200517_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate_popular',
            field=models.BooleanField(default=0, verbose_name='Выделения популяр. тарифа'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_summ',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_title_text',
            field=models.CharField(max_length=100, verbose_name='Описание тарифа'),
        ),
    ]
