# Generated by Django 3.0.2 on 2020-06-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sm_channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_title', models.CharField(max_length=100, verbose_name='Название канала')),
                ('sm_sub', models.CharField(choices=[('4K', '4K'), ('Детские', 'Детские'), ('Кино', 'Кино'), ('Музыкальные', 'Музыкальные'), ('Новостные', 'Новостные'), ('Развлекательные', 'Развлекательные'), ('Позновательные', 'Позновательные'), ('Региональные', 'Региональные'), ('Спортивные', 'Спортивные'), ('Эфирные', 'Эфирные')], max_length=15, verbose_name='Тематика')),
                ('sm_format', models.CharField(choices=[('SD', 'SD'), ('HD', 'HD'), ('4K', '4K')], max_length=3, verbose_name='Формат')),
            ],
            options={
                'verbose_name': 'Смотрешка канал',
                'verbose_name_plural': 'Смотрешка каналы',
            },
        ),
    ]
