# Generated by Django 3.0.2 on 2020-06-10 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sm_spisok_ch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_spisok_title', models.CharField(max_length=100, verbose_name='Наименование списка')),
                ('sm_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv.sm_channel')),
            ],
            options={
                'verbose_name': 'Список каналов',
                'verbose_name_plural': 'Списки каналов',
            },
        ),
    ]
