# Generated by Django 3.0.2 on 2020-06-13 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_sm_spisok_ch'),
    ]

    operations = [
        migrations.CreateModel(
            name='sm_tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_tarif_title', models.CharField(max_length=100, verbose_name='Наименование тарифа')),
                ('sm_tarif_count', models.IntegerField(verbose_name='Количество каналов')),
                ('sm_tarif_view', models.IntegerField(verbose_name='Количество устройств')),
                ('sm_tarif_summ', models.IntegerField(verbose_name='Абонентская плата')),
                ('sm_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv.sm_spisok_ch')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
